name: private_greeting
description: A simple private package for a Proof of Concept.
version: 1.0.1
homepage: https://github.com/KamoroMaximaIntegra/private_greeting

# Baris ini SANGAT PENTING
publish_to: 'https://npm.pkg.github.com/KamoroMaximaIntegra/'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0