name: Publish Flutter Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      # Langkah 1: Checkout repository (Tetap sama)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: GANTI DARI SETUP DART MENJADI SETUP FLUTTER
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Anda bisa ganti versi Flutter sesuai kebutuhan project
          flutter-version: '3.22.2' 
          channel: 'stable'

      # Langkah 3: Gunakan 'flutter pub' untuk autentikasi
      - name: Authenticate with GitHub Packages
        run: |
          echo "${{ secrets.DART_PUBLISH_TOKEN }}" | flutter pub token add https://npm.pkg.github.com/${{ github.repository_owner }}

      # Langkah 4: Gunakan 'flutter pub' untuk publish
      - name: Publish package
        run: flutter pub publish --force