name: Publish Flutter Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' 
          channel: 'stable'

      # ================== LANGKAH DEBUG BARU ==================
      # Langkah ini akan mencetak nilai sebenarnya dari variabel konteks
      # ke dalam log GitHub Actions Anda.
      - name: 'Debug: Print Context Variables'
        run: |
          echo "Repository Owner from variable: ${{ github.repository_owner }}"
          echo "Hardcoded Owner: KamoroMaximaIntegra"
          echo "Actor (who triggered): ${{ github.actor }}"
          echo "Full Target URL being used: https://npm.pkg.github.com/${{ github.repository_owner }}"

      # ================== PERUBAHAN PADA AUTENTIKASI ==================
      # Kita akan menggunakan URL yang di-hardcode untuk memastikan targetnya benar.
      - name: Authenticate with GitHub Packages (Using Hardcoded URL)
        run: |
          echo "${{ secrets.DART_PUBLISH_TOKEN }}" | flutter pub token add https://npm.pkg.github.com/KamoroMaximaIntegra

      - name: Publish package
        run: flutter pub publish --force